services:
  backend:
    volumes:
      - ./backend:/app/backend
    command: ["uvicorn", "app.api:app", "--reload", "--host", "0.0.0.0", "--port", "9000"]

  frontend:
    volumes:
      - ./frontend:/app/frontend
